services:
  db:
    image: docker.io/library/postgres:15.3-bullseye
    container_name: troycash_db_local
    init: true
    env_file:
      - .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=1000'
    ports:
      - "9002:5432"
    networks:
      - net
    logging:
      options:
        max-size: 1000m

  api_base:
    image: troycash_api_base_local:0.0.1
    container_name: troycash_api_base_local
    pull_policy: never
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    command: date
    env_file:
      - .env
    volumes:
      - .:/app
      - static_files_local:/app/static/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
    depends_on:
      - db
    logging:
      options:
        max-size: 1000m

  api:
    extends:
      service: api_base
    container_name: troycash_api_local
    command: /app/entrypoint.sh
    restart: always
    ports:
      - "9001:8000"

  pgadmin:
    image: dpage/pgadmin4:8.14
    container_name: troycash_pgadmin_local
    init: true
    env_file:
      - .env
    restart: always
    volumes:
      - pgadmin_local:/var/lib/pgadmin
    ports:
      - "9004:80"
    networks:
      - net
    logging:
      options:
        max-size: 1000m

networks:
  net:
    name: troycah_api_local
    external: false

volumes:
  pg_data: {}
  static_files_local: {}
  pgadmin_local: {}
